services:
  # Backend Service
  - type: web
    name: todo-backend
    runtime: docker
    repo: https://github.com/kamisettysudheer/todo-app.git
    branch: main
    dockerfilePath: ./todo-service/Dockerfile
    dockerContext: ./todo-service
    plan: starter
    region: oregon
    env: docker
    envVars:
      - key: PORT
        value: 8080
      - key: GIN_MODE
        value: release
    healthCheckPath: /health
    
  # Frontend Service  
  - type: web
    name: todo-frontend
    runtime: docker
    repo: https://github.com/kamisettysudheer/todo-app.git
    branch: main
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: starter
    region: oregon
    env: docker
    dockerBuildArgs:
      - name: REACT_APP_API_URL
        value: https://todo-backend.onrender.com
    healthCheckPath: /
